### ISSUE TITLE
https://git.door43.org/upgit/pnb_mrk_text_ulb.git

### ISSUE THREAD

**Issue by sea-liesch** [WycliffeAssociates/ScriptureRenderingPipeline#2]
https://scripturerenderingpipeline.azurewebsites.net/api/RenderDoc?url=https://git.door43.org/upgit/pnb_mrk_text_ulb.git&file_type=&filename=pnb-ulbgit.docx&separateVerses=N&separateChapters=N&columns=1&lineSpacing=1

This page isn’t workingscripturerenderingpipeline.azurewebsites.net is currently unable to handle this request.
HTTP ERROR 500

**Comment by rbnswartz** [comment]
@sea-liesch It won't handle the repo if you paste the .git after it. Works just fine for me without it.
