### ISSUE TITLE
support for SFM file extension

### ISSUE THREAD

**Issue by lversaw** [WycliffeAssociates/ScriptureRenderingPipeline#3]
Many USFM files have .sfm file extension instead of .usfm. For example, those found in https://git.door43.org/BCS-BIBLE/IRV-Assamese-OT/src/branch/master/Revised%20Stage%203

USFM Converter does not seem to recognize .sfm files.  It does convert the files if I rename them.

**Comment by rbnswartz** [comment]
#13 should handle that one for the web converter
