### ISSUE TITLE
Arabic code `arb` is being marked as "ltr"

### ISSUE THREAD

**Issue by mondele** [WycliffeAssociates/ScriptureRenderingPipeline#71]
In building the `langnames.json`, the direction for `arb` is listed as left-to-right. The other language code for Arabic, `ar`, is correctly listed as right-to-left.

This seems to be coming from the pipeline somewhere.

**Comment by rbnswartz** [comment]
langnames.json isn't generated from this pipeline. Are you referrring to https://td.unfoldingword.org/exports/langnames.json? That comes out of  translationDatabase or is this another langnames.json?

**Comment by mondele** [comment]
I think it's somewhere in the catalog pipeline. translationDatabase marks `arb` as `rtl`, and that's what it is in the **target** language database, but in the sources, it comes through as `ltr`. This issue is to try to find out how that information is getting into the pipeline so that we can update the source.

**Comment by rbnswartz** [comment]
Got more details from John Wood about this indeed it is a bug thank you.

**Comment by rbnswartz** [comment]
@mondele This is now fixed and pushed into production and all CDN content has been purged, you should be able to refresh the languages in writer and see the changes.
